language: php

php:
 - 7.2
 - 7.3
 - 7.4

before_script:
 - composer install --prefer-dist

script:
 - ./vendor/bin/phpstan analyze --no-progress

cache:
 directories:
  - $HOME/.composer/cache/files
  - $HOME/.composer/cache/vcs

notifications:
 email: false
