language: php

php:
 - 7.2
 - 7.3

before_script:
 - composer install --prefer-dist

script:
 - ./vendor/bin/phpstan analyze --no-progress

cache:
 directories:
  - vendor

notifications:
 email: false
